### ISSUE TITLE
왜 오류?

### ISSUE THREAD

**Issue by Byunggun** [rosa-yuri/C_study#1]
Q)나눗셈 연산자 사용 경우-오류. 왜?
cf. BG/ch4.c/q4_4_2(void)

**Comment by cutz-j** [comment]
{
```
	/*교과서 답안 
	int num = 3;
	num = num << 3;
	num = num >> 2;
	printf("%d \n", num);
	*/
```

	/*내 답안{오류}
	int num, multiply, divide; 

**> C에서는 위에서 선언된 변수를 다시 선언할 경우 에러가 날 수 있습니다.`**

	//int result;
	printf("num : ");
	scanf_s("%d", &num, sizeof(num));

**> 문자가 아닌 숫자를 sizeof로 추가하면, 에러가 날 수 있습니다. 문자에만 sizeof쓰시면 돼요.**

	multiply = num << 3; //2의 3승, 8
	divide = num >> 2; //2의 2승, 4

**> 비트연산자는 해당 범위(2진법)를 넘어갈 경우 0으로 표시됩니다. 2의 경우 (10)이므로 2자리를 왼쪽으로 넘어가면 해당 자리수가 없기 때문에 0이 됩니다. 이 경우 0이 되기 때문에, zero division error로 인해 연산이 되지 않습니다. 고로 이 코드에서는 4이상(2진법: 100)을 입력해줘야 코드가 정상적으로 실행됩니다.**

	//result = multiply / divide;
	printf("multiply 결과: %d \n", multiply);
	printf("divide 결과: %d \n", divide);
	//printf("최종 결과: %d \n", result);
	*/
	return 0;	 	
}
